---
# push_image_and_trigger_and_update_semver.yml
name: push_image_and_trigger_and_update_semver.yml
on:
  push:
    branches:
      - main
    paths:
      - 'pyproject.toml'

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Ls
        run: ls
      - name: list tags
        run: git --no-pager tag tag
