---
# push_image_and_trigger_and_update_semver.yml
name: push_image_and_trigger_and_update_semver.yml
on:
  push:
    branches:
      - main
    paths:
      - 'pyproject.toml'

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Ls
        run: ls
      - name: save current date
        run: |
          # do some operation that changes a file in the git repo
          date > time.txt
      - name: setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: commit
        run: |
          # Stage the file, commit and push
          git add time.txt
          git commit -m "new date commit"
          git push origin main
          git --no-pager tag
      - name: tags
        run: git --no-pager tag
      - name: Ls2
        run: ls -a

