---
# push_image_and_trigger_and_update_semver.yml
name: push_image_and_trigger_and_update_semver.yml
on:
  push:
    branches:
      - main
    paths:
      - 'pyproject.toml'

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Poetry Version
        id: poetry-version
        run: |
          ls
          SEMANTIC_VERSION=$(cat pyproject.toml)
          echo "semantic_version=$SEMANTIC_VERSION" >> $GITHUB_ENV
          echo "semantic_version=$SEMANTIC_VERSION"

#      - name: setup git config
#        run: |
#          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
#          git config user.name "GitHub Actions Bot"
#          git config user.email "<>"

      - name: tags
        run: |
          git fetch --all --tags
          git tag -a v${{ env.semantic_version }} -m "my version"
          git push origin v${{ env.semantic_version }}
